### ISSUE TITLE
set up tests

### ISSUE THREAD

**Issue by manuasir** [manuasir/laciobot#7]
The bot events need to be tested (unit tests with chai,mocha or something like that).

**Comment by gURLmeetsCode** [comment]
@manuasir Hey, did you ever get help on this issue? If not, I would love to help out!

**Comment by manuasir** [comment]
@gURLmeetsCode not yet! your help will be much appreciated :)

**Comment by gabrielsclimaco** [comment]
I gave it a try, but couldn't make any effective tests because I didn't know how should I mock the bot token.

If someone could help me on this I could test the code a little further.

**Comment by gabrielsclimaco** [comment]
@manuasir How can I call a function from a module (getCategory from quiz, for example). I'm been trying this for a while so I can test each function separately, but I can't call a function out of it's module
